"""Type stubs for the PyO3-generated ``tessera._native`` module.

Kept manual rather than auto-generated: the surface is small and stable, and a hand-written
stub gives Pyright exact signatures without needing the extension built during type checking.
"""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

REQUIRED_BLOCK_SIZE_TOKENS: int
__version__: str

class CkvDtype:
    Bf16: CkvDtype
    Fp8E4m3: CkvDtype
    Fp4E2m1: CkvDtype
    MixedBf16Fp8Fp4: CkvDtype
    def __repr__(self) -> str: ...

class CompressionScheme:
    @staticmethod
    def mla_latent(latent_dim: int, rope_key_dim: int) -> CompressionScheme: ...
    @staticmethod
    def mha_full(num_heads: int, head_dim: int) -> CompressionScheme: ...
    @staticmethod
    def dsa_hierarchical(coarse_dim: int, fine_dim: int, swa_window: int) -> CompressionScheme:
        """Deprecated (Sprint 5). Use v4_csa/v4_hca/v4_swa. See ADR-0020."""
    @staticmethod
    def v4_csa(
        k1: int,
        head_dim: int,
        num_heads: int,
        rope_dim: int,
        indexer_head_dim: int,
        num_indexer_heads: int,
        top_k: int,
    ) -> CompressionScheme: ...
    @staticmethod
    def v4_hca(k2: int, head_dim: int, num_heads: int, rope_dim: int) -> CompressionScheme: ...
    @staticmethod
    def v4_swa(window: int, head_dim: int, num_heads: int, rope_dim: int) -> CompressionScheme: ...
    def mla_latent_dim(self) -> int | None: ...
    def mla_rope_key_dim(self) -> int | None: ...
    def is_v4(self) -> bool: ...
    def bytes_per_token_per_layer(self) -> int: ...
    def __repr__(self) -> str: ...

class MlaBlockConfig:
    def __init__(
        self,
        scheme: CompressionScheme,
        num_layers: int,
        block_size_tokens: int,
        ckv_dtype: CkvDtype,
        device: int,
    ) -> None: ...
    @staticmethod
    def with_per_layer_schemes(
        schemes: list[CompressionScheme],
        block_size_tokens: int,
        ckv_dtype: CkvDtype,
        device: int,
    ) -> MlaBlockConfig:
        """Sprint 5: V4 hybrid per-layer config (CSA/HCA/SWA interleaved). See ADR-0021."""
    @property
    def num_layers(self) -> int: ...
    @property
    def block_size_tokens(self) -> int: ...
    def primary_block_bytes(self) -> int: ...
    def rope_block_bytes(self) -> int: ...
    def fp8_scale_block_bytes(self) -> int: ...
    def total_block_bytes(self) -> int: ...
    def compression_ratio_vs_mha_bf16(self) -> float: ...
    def scheme_for_layer(self, layer_idx: int) -> CompressionScheme: ...
    def has_per_layer_schemes(self) -> bool: ...
    def v4_block_size_lcm(self) -> int: ...
    def __repr__(self) -> str: ...
    def __sizeof__(self) -> int: ...

class BlockManager:
    def __init__(self, config: MlaBlockConfig, memory_bytes: int) -> None: ...
    @staticmethod
    def with_world(
        config: MlaBlockConfig,
        memory_bytes: int,
        rank: int,
        world: World,
    ) -> BlockManager: ...
    def allocate(self, req_id: int, token_start: int, token_end: int) -> int: ...
    def seal(self, block_id: int) -> tuple[int, int, bool]: ...
    def cow_fork(self, block_id: int, new_req_id: int) -> int: ...
    def free(self, block_id: int) -> None: ...
    def release_request(self, req_id: int) -> int: ...
    def increment_ref(self, block_id: int) -> int: ...
    def fill_primary_test_pattern(self, block_id: int, byte: int) -> None: ...
    def write_fp8_scales(self, block_id: int, scales: list[float]) -> None:
        """Sprint 5.1: atomic FP8 scale write under the block manager's read lock.

        Replaces the deprecated ``fp8_scales_ptr`` + ``ctypes.memmove`` pattern (audit
        C3 / ADR-0027). No-op when the active config has no FP8 scale region.
        """
    @property
    def used_blocks(self) -> int: ...
    @property
    def total_blocks(self) -> int: ...
    def utilization(self) -> float: ...
    # ── Sprint 3 multi-rank surface ───────────────────────────────────────
    @property
    def rank(self) -> int: ...
    @property
    def world_size(self) -> int: ...
    def global_id(self, block_id: int) -> tuple[int, int]: ...
    def transfer_request_to_rank(
        self, req_id: int, target: int, transport: MockTransport
    ) -> int: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def __sizeof__(self) -> int: ...

class ShareTable:
    def __init__(self) -> None: ...
    def add_share(self, req_id: int, block_id: int) -> None: ...
    def release_request(self, req_id: int) -> list[int]: ...
    def owners(self, block_id: int) -> list[int] | None: ...
    def shared_block_count(self) -> int: ...
    def sharing_rate(self) -> float: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...

class UsearchIndex:
    def __init__(
        self,
        dimensions: int,
        connectivity: int = 32,
        expansion_add: int = 200,
        expansion_search: int = 64,
    ) -> None: ...
    def add(self, block_id: int, descriptor: NDArray[np.float32]) -> None: ...
    def query(self, descriptor: NDArray[np.float32], k: int) -> list[tuple[int, float]]: ...
    def remove(self, block_id: int) -> None: ...
    def __len__(self) -> int: ...
    def name(self) -> str: ...
    def __repr__(self) -> str: ...

def metrics_snapshot_text() -> str: ...

# ────────────────────── Sprint 3: rank / world / transport ────────────────

class RankId:
    def __init__(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

class World:
    @staticmethod
    def single_node(local: int, size: int) -> World: ...
    @staticmethod
    def singleton() -> World: ...
    @staticmethod
    def multi_node(local: int, size: int, node_of: list[int]) -> World: ...
    @property
    def local(self) -> int: ...
    @property
    def size(self) -> int: ...
    def is_multi_node(self) -> bool: ...
    def has_peers(self) -> bool: ...
    def peers(self) -> list[int]: ...
    def __repr__(self) -> str: ...

class MockTransport:
    @staticmethod
    def new_world(size: int) -> list[MockTransport]: ...
    @staticmethod
    def singleton() -> MockTransport: ...
    def register_block_manager_peer(
        self, rank: int, manager: BlockManager, accept_req_id: int
    ) -> None: ...
    def events(self) -> list[str]: ...
    def event_count(self) -> int: ...
    def clear_events(self) -> None: ...
    @property
    def local(self) -> int: ...
    def name(self) -> str: ...
    def __repr__(self) -> str: ...

class DistributedSegmentIndex:
    def __init__(
        self,
        dimensions: int,
        world: World,
        transport: MockTransport,
        budget_us: int = 1000,
    ) -> None: ...
    def lookup_hash(self, content_hash: int) -> tuple[int, int] | None: ...
    def record_local_hit(self) -> None: ...
